services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel_shop_network

  mysql:
    image: mysql:8.1
    container_name: shop_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_shop
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3310:3306"
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - laravel_shop_network

  nginx:
    image: nginx:1.28
    container_name: shop_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_shop_network

networks:
  laravel_shop_network:
    driver: bridge

volumes:
  mysql_db:
